import { Geist, Geist_Mono, Roboto_Condensed, Bebas_Neue, Mona_Sans, Ubuntu, Roboto, Poppins } from "next/font/google";
import "./globals.css";

// Define fonts with CSS variables
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto_condensed = Roboto_Condensed({
  variable: "--roboto-condensed",
  subsets: ["latin"],
  weight: ["400", "700"],  // Removed 900 weight
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const bebasNeue = Bebas_Neue({
  variable: "--bebas-neue",
  subsets: ["latin"],
  weight: ["400"],
});

const monaSans = Mona_Sans({
  variable: "--font-mona-sans",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const ubuntu = Ubuntu({
  variable: "--font-ubuntu",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "400", "700"],
});

// Metadata for the app
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${roboto_condensed.variable} ${geistMono.variable} ${bebasNeue.variable} ${monaSans.variable} ${ubuntu.variable} ${roboto.variable} ${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
